---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: ubuntu-focal
    box: ubuntu/focal64
    memory: 2048
provisioner:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
verifier:
  name: testinfra
